version: '3.8'

networks:
  devkit-network:
    ipam:
      config:
        - subnet: 172.10.1.0/24

services:
  # Local npm registry for package development.
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    networks:
      devkit-network:
        ipv4_address: 172.10.1.2
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873
    volumes:
      - './.verdaccio/storage:/verdaccio/storage'
      - './.verdaccio/conf:/verdaccio/conf'
      - './.verdaccio/plugins:/verdaccio/plugins'
    restart: unless-stopped
