name: SSH Git Setup
description: Setup the SSH for git server connection. Commonly used for local git servers.
author: ccosming
branding:
  color: gray-dark
  icon: terminal

inputs:
  git-server-url:
    description: The git server url to be used for the SSH connection
    required: true
  git-server-port:
    description: The git server port to be used for the SSH connection
    required: true
  ssh-private-key:
    description: The private key to be used for the SSH connection
    required: true
  ssh-passphrase:
    description: The passphrase related to the private key
    required: true
  ssh-auth-sock:
    description: The ssh auth sock to be used for the SSH connection
    required: true

runs:
  using: composite
  steps:
    - name: 'Setup SSH with a passphrase to connect to git server'
      env:
        GIT_SERVER_URL: ${{inputs.git-server-url}}
        GIT_SERVER_PORT: ${{inputs.git-server-port}}
        SSH_PRIVATE_KEY: ${{inputs.ssh-private-key}}
        SSH_PASSPHRASE: ${{inputs.ssh-passphrase}}
        SSH_AUTH_SOCK: ${{inputs.ssh-auth-sock}}
      shell: bash
      run: |
        ssh-agent -a $SSH_AUTH_SOCK
        echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add -
        cat << EOF > "$HOME/.ssh/config"
        Host $GIT_SERVER_URL
          Port $GIT_SERVER_PORT
          StrictHostKeyChecking no
        EOF
