$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  changeset:
    - '.changeset/**/*'
  dist:
    - './dist/**/*'

tasks:
  # Publishes the library to npm.
  publish:
    command: 'pnpm changeset publish'
    description: 'Publishes the library to npm using changesets'
    type: run
    inputs:
      - '@group(dist)'
    deps:
      - 'build'

  # Versioning the library.
  version:
    command: 'pnpm changeset version'
    description: 'Versioning the library using changesets'
    type: run
    inputs:
      - '@group(src)'
      - '@group(changeset)'
    deps:
      - 'test'
