services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    volumes:
      - './.verdaccio/storage:/verdaccio/storage'
      - './.verdaccio/conf:/verdaccio/conf'
      - './.verdaccio/plugins:/verdaccio/plugins'
    restart: unless-stopped