$schema: 'https://moonrepo.dev/schemas/project.json'

type: configuration
language: typescript
stack: systems
platform: node
tags:
  - node
  - package

fileGroups:
  src:
    - 'src/**/*'
    - 'package.json'
    - 'tsup.config.ts'
    - 'tsconfig.json'

tasks:
  build:
    command: 'pnpm build'
    description: 'Build the application'
    type: build
    inputs:
      - '@group(src)'
    outputs:
      - '@group(dist)'

  test:
    command: 'echo "🧪 This package has no tests yet"'
    description: 'Run the tests'
    type: test
